// generator/templates/coasm_summary.h.tpl
// Template for C++ Summary Header (coasm_summary.h)
// Generated by coasm_infra.generator from ISAModel

#ifndef COASM_SUMMARY_H
#define COASM_SUMMARY_H

// Auto-generated COASM summary header from coasm_infra

#include <cstdint>
#include <cstddef> // For size_t if needed

// --- Opcodes Enum ---
enum class CoasmOpcode : uint16_t {
{% for instr in instructions %}
    {{ instr.name }} = {{ instr.value }},
{%- endfor %}
};

// --- Types Enum ---
enum class CoasmOpType : uint8_t {
{% for typ in types %}
    {{ typ.name }} = {{ typ.value }},
{%- endfor %}
};

// --- Formats Enum ---
enum class CoasmFormat : uint8_t {
{% for fmt in formats %}
    {{ fmt.name }} = {{ fmt.value }},
{%- endfor %}
};

// --- Helper Function Declarations ---
// These functions would typically be defined in a .cpp file
// or implemented inline here.

const char* get_opcode_name(CoasmOpcode op);
const char* get_type_name(CoasmOpType type);
const char* get_format_name(CoasmFormat fmt);

#endif // COASM_SUMMARY_H
